#!/bin/bash

_get_ziplink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    echo "aHR0cHM6Ly9naXRodWIuY29tL2FzaHR5LWRyb25lL0NhdFRlbXBsYXRlL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
}

_get_repolink () {
    local regex
    local rlink
    regex='(https?)://github.com/.+/.+'
    rlink-`echo "aHR0cHM6Ly9naXRodWIuY29tL2FzaHR5LWRyb25lL0NhdFRlbXBsYXRl" | base64 -d`
    echo "$rlink"
}


_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run_catpack_git() {
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO = "https://github.com/sandy1709/catuserbot"
ACTIVE_BRANCH_NAME = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_run_cat_git() {
    local repolink=$(_get_repolink)
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO="'$repolink'"
ACTIVE_BRANCH_NAME = "'$UPSTREAM_REPO_BRANCH'" or "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_set_bot () {
    local zippath
    zippath="catuserbot.zip"
    wget -q $(_get_ziplink) -O "$zippath"
    CATPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    rm -rf "$zippath"
    _run_catpack_git
    cd $CATPATH
    _run_cat_git
    chmod -R 755 bin
    sh start.sh
}

_set_bot
